#pragma once

// Oracle gains for the D-04 below-horizon (lower-hemisphere) construction on height layouts.
// Generated by tests/reference/gen_ear_reference.py
//   numpy 2.5.3, ear 2.1.0
// Generated — do not edit; regenerate per tests/reference/README.md
//
// Oracle: the EBU ADM Renderer (PyPI `ear` 2.1.0, github.com/ebu/ebu_adm_renderer), the reference
// implementation of ITU-R BS.2127 -- independent of the code under test. Speaker positions are
// parsed from layoutDefs in src/IO/SpeakerLayout.cpp.
//
// Every case below lies in ear's VirtualNgon (nadir-cap) region, where the D-04 construction
// matches ear exactly. The -30..0 deg band is deliberately NOT pinned against ear: there ear uses
// bilinear QuadRegions while SpatialCore uses triplets (RESEARCH Reference Data C, F4) -- test that
// band by properties instead. Gains are L2-normalised; unused trailing slots are zero.

namespace spatialcore_ref
{

struct EarCase { float azimuthDeg; float elevationDeg; float gains[16]; };

// S5_1_2: 7 speakers, gains in layoutDefs speaker order (az/el deg): 30/0, -30/0, 0/0, 110/0, -110/0, 90/45, -90/45
inline constexpr int kEarNumSpeakers_S5_1_2 = 7;
inline constexpr EarCase kEarCases_S5_1_2[] = {
    { 30.0f, -60.0f, { 0.8506508f, 0.2628656f, 0.2628656f, 0.2628656f, 0.2628656f, 0.0000000f, 0.0000000f } },
    { 180.0f, -60.0f, { 0.0081453f, 0.0081453f, 0.0081453f, 0.7070364f, 0.7070364f, 0.0000000f, 0.0000000f } },
    { -100.0f, -75.0f, { 0.3637489f, 0.4175284f, 0.3637489f, 0.3637489f, 0.6547749f, 0.0000000f, 0.0000000f } },
    { 30.0f, -90.0f, { 0.4472136f, 0.4472136f, 0.4472136f, 0.4472136f, 0.4472136f, 0.0000000f, 0.0000000f } },
};

// S7_1_4: 11 speakers, gains in layoutDefs speaker order (az/el deg): 30/0, -30/0, 0/0, 90/0, -90/0, 135/0, -135/0, 45/45, -45/45, 135/45, -135/45
inline constexpr int kEarNumSpeakers_S7_1_4 = 11;
inline constexpr EarCase kEarCases_S7_1_4[] = {
    { 30.0f, -60.0f, { 0.8300495f, 0.2276759f, 0.2276759f, 0.2276759f, 0.2276759f, 0.2276759f, 0.2276759f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { 0.0f, -45.0f, { 0.1164798f, 0.1164798f, 0.9584335f, 0.1164798f, 0.1164798f, 0.1164798f, 0.1164798f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { 180.0f, -70.0f, { 0.2674711f, 0.2674711f, 0.2674711f, 0.2674711f, 0.2674711f, 0.5666992f, 0.5666992f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { -100.0f, -75.0f, { 0.3201575f, 0.3201575f, 0.3201575f, 0.3201575f, 0.5742917f, 0.3201575f, 0.3970957f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { 30.0f, -90.0f, { 0.3779645f, 0.3779645f, 0.3779645f, 0.3779645f, 0.3779645f, 0.3779645f, 0.3779645f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
};

// S9_1_6: 15 speakers, gains in layoutDefs speaker order (az/el deg): 30/0, -30/0, 0/0, 90/0, -90/0, 135/0, -135/0, 60/0, -60/0, 45/45, -45/45, 90/45, -90/45, 135/45, -135/45
inline constexpr int kEarNumSpeakers_S9_1_6 = 15;
inline constexpr EarCase kEarCases_S9_1_6[] = {
    { 45.0f, -75.0f, { 0.4549079f, 0.2893633f, 0.2893633f, 0.2893633f, 0.2893633f, 0.2893633f, 0.2893633f, 0.4549079f, 0.2893633f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { -90.0f, -60.0f, { 0.2041241f, 0.2041241f, 0.2041241f, 0.2041241f, 0.8164966f, 0.2041241f, 0.2041241f, 0.2041241f, 0.2041241f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { 120.0f, -50.0f, { 0.1486895f, 0.1486895f, 0.1486895f, 0.4781848f, 0.1486895f, 0.7852256f, 0.1486895f, 0.1486895f, 0.1486895f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
    { 30.0f, -90.0f, { 0.3333333f, 0.3333333f, 0.3333333f, 0.3333333f, 0.3333333f, 0.3333333f, 0.3333333f, 0.3333333f, 0.3333333f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f } },
};

} // namespace spatialcore_ref
