#!/usr/bin/env python3
"""Oracle gains for the D-04 lower-hemisphere construction, from the EBU ADM Renderer (PyPI `ear` 2.1.0,
the ITU-R BS.2127 reference implementation).

Only directions that ear handles with its VirtualNgon (nadir cap) region are emitted as exact oracle values.
Where ear uses a bilinear QuadRegion (the -30..0 band) SpatialCore uses triplets, and the two differ by up to
~0.055 (more on 5.1.4, RESEARCH F4), so those directions are NOT pinned against ear.  Also asserts the
'meridian' case (directly under an ear-level speaker) where both agree exactly: gain 1 on that speaker.

Offline tool, NOT run in CI.  Layouts are parsed from src/IO/SpeakerLayout.cpp so the oracle follows the real
table.  Prints a complete C++ header on stdout (redirect into tests/reference/EarReference.h); diagnostics go
to stderr.  Exits non-zero, printing nothing on stdout, if a self-check fails.
"""
import sys
import warnings

warnings.filterwarnings("ignore")

from importlib.metadata import version as pkg_version

import numpy as np
from ear.core import point_source
from ear.core.geom import PolarPosition
from ear.core.layout import Channel, Layout
from ear.core.point_source import VirtualNgon

from layouts_from_cpp import load


def check(cond, msg):
    if not cond:
        sys.exit(f"gen_ear_reference.py: SELF-CHECK FAILED: {msg}")


def ear_panner(spk):
    ch = [Channel(name=("T+000" if el == 90 else f"S{i:02d}"), polar_position=PolarPosition(az, el, 1.0))
          for i, (az, el, _c) in enumerate(spk)]
    return point_source.configure(Layout(name="custom", channels=ch))


def ear_gains(panner, az, el):
    """Returns (gains in layoutDefs speaker order, handled_by_VirtualNgon).
    ear: +az = left, x = right (mirror of SpatialCore's x axis) -- gains are unaffected by the mirror."""
    a, e = np.radians(az), np.radians(el)
    pos = np.array([np.sin(-a) * np.cos(e), np.cos(a) * np.cos(e), np.sin(e)])
    for r in panner.psp.regions:
        pv = r.handle_remap(pos, panner.psp.num_channels)
        if pv is not None:
            g = np.dot(panner.downmix, pv)
            return g / np.linalg.norm(g), isinstance(r, VirtualNgon)
    raise RuntimeError("ear found no region")


CASES = {
    "S5_1_2": [(30, -60), (180, -60), (-100, -75), (30, -90)],
    "S7_1_4": [(30, -60), (0, -45), (180, -70), (-100, -75), (30, -90)],
    "S9_1_6": [(45, -75), (-90, -60), (120, -50), (30, -90)],
}


def fmt(v, decimals):
    v = round(float(v), decimals) + 0.0      # + 0.0 turns -0.0 into 0.0
    return f"{v:.{decimals}f}f"


def main():
    L = load()
    body = []
    for name, pts in CASES.items():
        spk = L[name]["spk"]
        check(len(spk) <= 16, f"{name} has {len(spk)} speakers; EarCase holds 16")
        p = ear_panner(spk)
        order = ", ".join(f"{az}/{el}" for az, el, _c in spk)
        body.append(f"// {name}: {len(spk)} speakers, gains in layoutDefs speaker order (az/el deg): {order}")
        body.append(f"inline constexpr int kEarNumSpeakers_{name} = {len(spk)};")
        body.append(f"inline constexpr EarCase kEarCases_{name}[] = {{")
        for az, el in pts:
            g, ngon = ear_gains(p, az, el)
            check(ngon, f"{name} ({az},{el}) is not in ear's VirtualNgon (nadir-cap) region")
            check(abs(float(np.dot(g, g)) - 1.0) < 1e-12, f"{name} ({az},{el}) power is not 1")
            body.append(f"    {{ {float(az):.1f}f, {float(el):.1f}f, {{ " + ", ".join(fmt(v, 7) for v in g) + " } },")
        body.append("};")
        body.append("")
        g, _ = ear_gains(p, spk[0][0], -15.0)
        check(abs(g[0] - 1.0) < 1e-9, f"{name}: meridian case (az {spk[0][0]}, el -15) must be exactly 1 "
                                       f"on the speaker above, got {g[0]!r}")

    lines = [
        "#pragma once",
        "",
        "// Oracle gains for the D-04 below-horizon (lower-hemisphere) construction on height layouts.",
        "// Generated by tests/reference/gen_ear_reference.py",
        f"//   numpy {np.__version__}, ear {pkg_version('ear')}",
        "// Generated — do not edit; regenerate per tests/reference/README.md",
        "//",
        "// Oracle: the EBU ADM Renderer (PyPI `ear` 2.1.0, github.com/ebu/ebu_adm_renderer), the reference",
        "// implementation of ITU-R BS.2127 -- independent of the code under test. Speaker positions are",
        "// parsed from layoutDefs in src/IO/SpeakerLayout.cpp.",
        "//",
        "// Every case below lies in ear's VirtualNgon (nadir-cap) region, where the D-04 construction",
        "// matches ear exactly. The -30..0 deg band is deliberately NOT pinned against ear: there ear uses",
        "// bilinear QuadRegions while SpatialCore uses triplets (RESEARCH Reference Data C, F4) -- test that",
        "// band by properties instead. Gains are L2-normalised; unused trailing slots are zero.",
        "",
        "namespace spatialcore_ref",
        "{",
        "",
        "struct EarCase { float azimuthDeg; float elevationDeg; float gains[16]; };",
        "",
    ] + body + ["} // namespace spatialcore_ref"]

    print("\n".join(lines))
    print(f"gen_ear_reference.py: {sum(len(v) for v in CASES.values())} VirtualNgon cases, "
          f"{len(CASES)} meridian checks passed", file=sys.stderr)


if __name__ == "__main__":
    main()
