#!/usr/bin/env python3
"""Reference values for SpatialCore evalSH: real SH, ACN order, SN3D, NO Condon-Shortley phase (D-10, D-11c).

Offline tool, NOT run in CI.  Requires numpy + scipy (pins in tests/reference/README.md).
Prints a complete C++ header on stdout (redirect into tests/reference/ShReference.h); diagnostics go to
stderr.  Exits non-zero, printing nothing on stdout, if either self-check fails:
  1. the two independent scipy routes (lpmv with the CS phase removed; sph_harm_y) agree below 1e-12;
  2. the SN3D addition theorem  sum_m Y_lm^2 == 1  holds below 1e-12 for l = 0..6 on 4000 seeded directions.

Convention: az = 0 front, +az toward +Y (left), radians; el = 0 horizon, +el up.
  ACN = l*l + l + m ; m > 0 -> cos(m*az) ; m < 0 -> sin(|m|*az).
"""
import math
import sys

import numpy as np
import scipy
from scipy.special import factorial, lpmv, sph_harm_y

AZ_DEG, EL_DEG = 64.0, 10.0


def check(cond, msg):
    if not cond:
        sys.exit(f"gen_sh_reference.py: SELF-CHECK FAILED: {msg}")


def sn3d(acn, az, el):                       # route 1: associated Legendre (CS phase removed)
    l = math.isqrt(acn); m = acn - l * l - l; am = abs(m)
    P = ((-1) ** am) * lpmv(am, l, np.sin(el))
    N = math.sqrt((2 - (1 if m == 0 else 0)) * factorial(l - am) / factorial(l + am))
    return N * P * (np.cos(am * az) if m >= 0 else np.sin(am * az))


def sn3d_route2(acn, az, el):                # route 2: scipy complex SH -> real SH -> SN3D scale
    l = math.isqrt(acn); m = acn - l * l - l
    Y = sph_harm_y(l, abs(m), np.pi / 2 - el, az)
    r = Y.real if m == 0 else (math.sqrt(2) * Y.real * ((-1) ** m) if m > 0 else math.sqrt(2) * Y.imag * ((-1) ** (-m)))
    return r * math.sqrt(4 * np.pi / (2 * l + 1))


def fmt(v, decimals):
    v = round(float(v), decimals) + 0.0      # + 0.0 turns -0.0 into 0.0
    return f"{v:.{decimals}f}f"


def main():
    az, el = math.radians(AZ_DEG), math.radians(EL_DEG)
    ref = [float(sn3d(c, az, el)) for c in range(49)]
    alt = [float(sn3d_route2(c, az, el)) for c in range(49)]
    route_diff = max(abs(a - b) for a, b in zip(ref, alt))
    check(route_diff < 1e-12, f"two scipy routes disagree by {route_diff:.3e}")

    rng = np.random.default_rng(1)
    A = rng.uniform(-np.pi, np.pi, 4000)
    E = np.arcsin(rng.uniform(-1, 1, 4000))
    worst = 0.0
    for l in range(7):                        # addition theorem: sum_m Y_lm^2 == 1 (SN3D)
        s = sum(sn3d(c, A, E) ** 2 for c in range(l * l, (l + 1) ** 2))
        dev = float(np.abs(s - 1).max())
        check(dev < 1e-12, f"SN3D addition theorem fails at order {l}: max |sum - 1| = {dev:.3e}")
        worst = max(worst, dev)

    lines = [
        "#pragma once",
        "",
        "// Reference values for spatialcore::evalSH -- spherical harmonics up to order 6 (49 channels).",
        "// Generated by tests/reference/gen_sh_reference.py",
        f"//   numpy {np.__version__}, scipy {scipy.__version__}",
        "// Generated — do not edit; regenerate per tests/reference/README.md",
        "//",
        "// Oracle: scipy.special (lpmv with the Condon-Shortley phase removed, cross-checked against",
        "// sph_harm_y; agreement < 1e-12) -- independent of the code under test.",
        "// Self-check: SN3D addition theorem sum_m Y_lm^2 == 1 holds < 1e-12 for l = 0..6.",
        "//",
        "// Convention (D-10): real SH, ACN channel order (acn = l*l + l + m; m > 0 uses cos(m az),",
        "// m < 0 uses sin(|m| az)), SN3D normalisation, no Condon-Shortley phase, angles in radians,",
        "// az 0 = front, +az toward +Y (left), el 0 = horizon, +el up.",
        "",
        "namespace spatialcore_ref",
        "{",
        "",
        f"inline constexpr float kShRefAzimuthDeg = {AZ_DEG:.1f}f;",
        f"inline constexpr float kShRefElevationDeg = {EL_DEG:.1f}f;",
        "",
        "inline constexpr float kShRef_az64_el10[49] = {",
    ]
    for c in range(49):
        lines.append(f"    {fmt(ref[c], 9)},  // ACN {c}")
    lines += ["};", "", "} // namespace spatialcore_ref"]

    print("\n".join(lines))
    print(f"gen_sh_reference.py: routes agree to {route_diff:.3e}; addition theorem worst {worst:.3e}; "
          f"min |Y| = {min(abs(v) for v in ref):.7f} at ACN {int(np.argmin(np.abs(ref)))}", file=sys.stderr)


if __name__ == "__main__":
    main()
