#pragma once

// Textbook panning-law reference values (D-13, D-14, D-16) in layoutDefs speaker order.
// Generated by tests/reference/gen_panning_reference.py
//   numpy 2.5.3
// Generated — do not edit; regenerate per tests/reference/README.md
//
// Oracles (published formulas, independent of the code under test):
//   VBAP  Pulkki 1997 / Pernaux-Boussard-Jot DAFx-98 s2.2.1:  g = L^-1 p, then g / ||g||_2
//   VBIP  Pernaux-Boussard-Jot DAFx-98 s2.2.2 (single band): g_i = sqrt(G_i / sum G), G = L^-1 p
//   DBAP  Lossius et al. ICMC 2009 eq (2)-(5): v_i = k / d_i^a, a = 2 (R = 12.04 dB), r_s = 0,
//         d^2 clamped >= 0.001, speaker radius 1, source at distance * unit direction
// Speaker positions are parsed from layoutDefs in src/IO/SpeakerLayout.cpp.
// Self-checks: VBAP/VBIP power == 1 (1e-12); VBIP energy vector points at the source (1e-9 rad);
// DBAP dist 0.5 reproduces the pre-existing code golden (1e-6); each 7.1.4 pin's triplet is the
// unique minimum-sum enclosing triple over all |det| >= 0.01 triples by > 1e-4 (no coplanar tie).
//
// Speaker order -- Quad: 45, -45, 135, -135 | 5.0: 30, -30, 0, 110, -110 |
// 7.1.4 (az/el): 30/0, -30/0, 0/0, 90/0, -90/0, 135/0, -135/0, 45/45, -45/45, 135/45, -135/45

namespace spatialcore_ref
{

// VBAP, Quad, az 30 el 0
inline constexpr float kVbap_Quad_az30[4] = { 0.9659258f, 0.2588190f, 0.0000000f, 0.0000000f };
// VBIP, Quad, az 30 el 0
inline constexpr float kVbip_Quad_az30[4] = { 0.8880738f, 0.4597008f, 0.0000000f, 0.0000000f };
// VBAP, 5.0, az 10 el 0
inline constexpr float kVbap_S5_0_az10[5] = { 0.4527072f, 0.0000000f, 0.8916592f, 0.0000000f, 0.0000000f };
// VBIP, 5.0, az 10 el 0
inline constexpr float kVbip_S5_0_az10[5] = { 0.5802964f, 0.0000000f, 0.8144053f, 0.0000000f, 0.0000000f };
// VBAP, 5.0, az 50 el 0
inline constexpr float kVbap_S5_0_az50[5] = { 0.9300936f, 0.0000000f, 0.0000000f, 0.3673226f, 0.0000000f };
// VBIP, 5.0, az 50 el 0
inline constexpr float kVbip_S5_0_az50[5] = { 0.8466885f, 0.0000000f, 0.0000000f, 0.5320889f, 0.0000000f };

// DBAP, Quad, az 30 el 0, distance 1.0
inline constexpr float kDbap_Quad_az30_dist1[4] = { 0.9984304f, 0.0459007f, 0.0270259f, 0.0173052f };
// DBAP, Quad, az 30 el 0, distance 0.5 (equals the pre-existing code golden, F2)
inline constexpr float kDbap_Quad_az30_dist05[4] = { 0.9390509f, 0.2691336f, 0.1768006f, 0.1203831f };

// MDAP: a PORT of the code's ring construction (main direction + 8 aux points on a ring at
// alpha = clamp(0.9 * 180 / N, 5, 30) degrees, amplitude-summed 2D VBAP, L2-normalised). This is a
// cross-check of the ring geometry, not an independent oracle (RESEARCH F3); it depends on the
// ring start phase (~1% of gain). Compare at tolerance 5e-4.
inline constexpr float kMdapPort_Quad_az30[4] = { 0.9478133f, 0.3132631f, 0.0592973f, 0.0000000f };
inline constexpr float kMdapPort_S5_0_az10[5] = { 0.6412997f, 0.2999306f, 0.7051913f, 0.0384905f, 0.0000000f };

// 3D VBAP on 7.1.4: each pin lies inside a single minimum-sum triplet (no coplanar tie, RESEARCH F5).
struct Vbap3DCase { float azimuthDeg; float elevationDeg; float gains[11]; };

inline constexpr Vbap3DCase kVbap3D_S7_1_4[4] = {
    { 0.0f, 30.0f, { 0.0000000f, 0.0000000f, 0.7157629f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.4938033f, 0.4938033f, 0.0000000f, 0.0000000f } },  // triplet 2, 7, 8
    { 60.0f, 20.0f, { 0.3733918f, 0.0000000f, 0.0000000f, 0.6244854f, 0.0000000f, 0.0000000f, 0.0000000f, 0.6860004f, 0.0000000f, 0.0000000f, 0.0000000f } },  // triplet 0, 3, 7
    { 10.0f, 10.0f, { 0.1193867f, 0.0000000f, 0.9451641f, 0.0000000f, 0.0000000f, 0.0000000f, 0.0000000f, 0.3039929f, 0.0000000f, 0.0000000f, 0.0000000f } },  // triplet 0, 2, 7
    { 90.0f, 30.0f, { 0.0000000f, 0.0000000f, 0.0000000f, 0.7157629f, 0.0000000f, 0.0000000f, 0.0000000f, 0.4938033f, 0.0000000f, 0.4938033f, 0.0000000f } },  // triplet 3, 7, 9
};

} // namespace spatialcore_ref
