#pragma once

// Reference values for spatialcore::evalSH -- spherical harmonics up to order 6 (49 channels).
// Generated by tests/reference/gen_sh_reference.py
//   numpy 2.5.3, scipy 1.18.1
// Generated — do not edit; regenerate per tests/reference/README.md
//
// Oracle: scipy.special (lpmv with the Condon-Shortley phase removed, cross-checked against
// sph_harm_y; agreement < 1e-12) -- independent of the code under test.
// Self-check: SN3D addition theorem sum_m Y_lm^2 == 1 holds < 1e-12 for l = 0..6.
//
// Convention (D-10): real SH, ACN channel order (acn = l*l + l + m; m > 0 uses cos(m az),
// m < 0 uses sin(|m| az)), SN3D normalisation, no Condon-Shortley phase, angles in radians,
// az 0 = front, +az toward +Y (left), el 0 = horizon, +el up.

namespace spatialcore_ref
{

inline constexpr float kShRefAzimuthDeg = 64.0f;
inline constexpr float kShRefElevationDeg = 10.0f;

inline constexpr float kShRef_az64_el10[49] = {
    1.000000000f,  // ACN 0
    0.885139345f,  // ACN 1
    0.173648178f,  // ACN 2
    0.431711304f,  // ACN 3
    0.661859328f,  // ACN 4
    0.266221118f,  // ACN 5
    -0.454769466f,  // ACN 6
    0.129844715f,  // ACN 7
    -0.517101179f,  // ACN 8
    -0.156990472f,  // ACN 9
    0.256992782f,  // ACN 10
    -0.460313171f,  // ACN 11
    -0.247381933f,  // ACN 12
    -0.224509734f,  // ACN 13
    -0.200784767f,  // ACN 14
    -0.738582103f,  // ACN 15
    -0.674922629f,  // ACN 16
    -0.072126116f,  // ACN 17
    -0.337050780f,  // ACN 18
    -0.338889873f,  // ACN 19
    0.265901611f,  // ACN 20
    -0.165287635f,  // ACN 21
    0.263332930f,  // ACN 22
    -0.339326697f,  // ACN 23
    -0.168277111f,  // ACN 24
    -0.417724629f,  // ACN 25
    -0.351597254f,  // ACN 26
    0.075659158f,  // ACN 27
    -0.309215491f,  // ACN 28
    0.255799553f,  // ACN 29
    0.281017541f,  // ACN 30
    0.124761778f,  // ACN 31
    0.241585619f,  // ACN 32
    0.355948351f,  // ACN 33
    -0.087663041f,  // ACN 34
    0.497824827f,  // ACN 35
    0.249225837f,  // ACN 36
    -0.240578412f,  // ACN 37
    0.302578333f,  // ACN 38
    0.083335370f,  // ACN 39
    0.168630638f,  // ACN 40
    0.363217706f,  // ACN 41
    -0.132121339f,  // ACN 42
    0.177153112f,  // ACN 43
    -0.131748693f,  // ACN 44
    0.392062093f,  // ACN 45
    0.075441251f,  // ACN 46
    0.286710187f,  // ACN 47
    0.559770395f,  // ACN 48
};

} // namespace spatialcore_ref
